import DS from 'ember-data';

var Quest = DS.Model.extend({
	name: DS.attr("string", { defaultValue: "" }),
	type: DS.attr("string", { defaultValue: "Acana" }),
	expansion: DS.attr("string", { defaultValue: "Base" }),
	flavor: DS.attr("string", { defaultValue: "" }),

	isPlotQuest: DS.attr("boolean", { defaultValue: false }),

	requiredClerics: DS.attr("number", { defaultValue: 0 }),
	requiredFighters: DS.attr("number", { defaultValue: 0 }),
	requiredRogues: DS.attr("number", { defaultValue: 0 }),
	requiredWizards: DS.attr("number", { defaultValue: 0 }),
	requiredGold: DS.attr("number", { defaultValue: 0 }),
	requiredAdventurers: DS.attr("number", { defaultValue: 0 }),

	rewardPoints: DS.attr("number", { defaultValue: 0 }),
	rewardClerics: DS.attr("number", { defaultValue: 0 }),
	rewardFighters: DS.attr("number", { defaultValue: 0 }),
	rewardRogues: DS.attr("number", { defaultValue: 0 }),
	rewardWizards: DS.attr("number", { defaultValue: 0 }),
	rewardGold: DS.attr("number", { defaultValue: 0 }),
	rewardAdventurers: DS.attr("number", { defaultValue: 0 }),

	rewardIntrigue: DS.attr("number", { defaultValue: 0 }),
	rewardCorruption: DS.attr("number", { defaultValue: 0 }),
	rewardEffect: DS.attr("string", { defaultValue: "" })
});

Quest.reopenClass({
	FIXTURES: [
		{
			id: 1,
			name: "Domesticate Owlbears",
			type: "Arcana",
			requiredClerics: 1,
			requiredWizards: 2,
			rewardPoints: 8,
			rewardFighters: 1,
			rewardGold: 2
		},
		{
			id: 2,
			name: "Explore Ahghairon's Tower",
			type: "Arcana",
			isPlotQuest: true,
			requiredFighters: 1,
			requiredWizards: 2,
			requiredGold: 2,
			rewardPoints: 6,
			rewardEffect: "Whenever you take an action that provides any wizards, also draw an Intrigue card."
		},
		{
			id: 3,
			name: "Expose Red Wizards' Spies",
			type: "Arcana",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 2,
			requiredWizards: 2,
			requiredGold: 2,
			rewardPoints: 20,
			rewardIntrigue: 1,
		},
		{
			id: 4,
			name: "Host Festival For Sune",
			type: "Arcana",
			requiredFighters: 2,
			requiredWizards: 2,
			requiredGold: 4,
			rewardClerics: 2,
			rewardPoints: 9,
		},
		{
			id: 5,
			name: "Infiltrate Halaster's Circle",
			type: "Arcana",
			requiredWizards: 5,
			requiredGold: 2,
			rewardPoints: 25,
		},
		{
			id: 6,
			name: "Investigate Aberrant Infestation",
			type: "Arcana",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredWizards: 2,
			rewardPoints: 13,
			rewardIntrigue: 1,
		},
		{
			id: 7,
			name: "Recover the Magister's Orb",
			type: "Arcana",
			isPlotQuest: true,
			requiredRogues: 3,
			requiredWizards: 2,
			rewardPoints: 6,
			rewardEffect: "Once per round, you can assign an agent to a space containing an opponent's agent."
		},
		{
			id: 8,
			name: "Recruit for Blackstaff Academy",
			type: "Arcana",
			requiredFighters: 1,
			requiredRogues: 1,
			requiredWizards: 2,
			requiredGold: 4,
			rewardPoints: 6,
			rewardWizards: 3
		},
		{
			id: 9,
			name: "Research Chronomancy",
			type: "Arcana",
			requiredWizards: 2,
			requiredGold: 4,

			rewardPoints: 4,
			rewardWizards: 1,
			rewardEffect: "Return 1 of your assigned agents to your pool."
		},
		{
			id: 10,
			name: "Retrieve Ancient Artifacts",
			type: "Arcana",
			requiredFighters: 2,
			requiredRogues: 1,
			requiredWizards: 2,
			rewardPoints: 11,
			rewardGold: 4
		},
		{
			id: 11,
			name: "Steal Spellbook from Silverhand",
			type: "Arcana",
			requiredFighters: 1,
			requiredRogues: 2,
			requiredWizards: 2,
			rewardPoints: 7,
			rewardGold: 4,
			rewardIntrigue: 2
		},
		{
			id: 12,
			name: "Study the Illusk Arch",
			type: "Arcana",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredWizards: 2,
			rewardPoints: 8,
			rewardEffect: "Whenever you complete an Arcana Quest, you score 2 points."
		},
		{
			id: 13,
			name: "Deal with the Black Viper",
			type: "Arcana",
			expansion: "Undermountain",
			requiredFighters: 1,
			requiredRogues: 4,
			requiredWizards: 2,
			requiredGold: 5,
			rewardPoints: 10,
			rewardIntrigue: 4,
			rewardEffect: "As you draw each card, you can play it immediately as part of completing this quest."
		},
		{
			id: 14,
			name: "Establish Wizard Academy",
			type: "Arcana",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 3,
			requiredWizards: 3,
			rewardPoints: 12,
			rewardEffect: "Whenever you take an Arcana Quest, take a wizard from the supply an place it in your Tavern."
		},
		{
			id: 15,
			name: "Explore Trobriand's Graveyard",
			type: "Arcana",
			expansion: "Undermountain",
			requiredFighters: 2,
			requiredRogues: 3,
			requiredWizards: 4,
			requiredGold: 6,
			rewardPoints: 40
		},
		{
			id: 16,
			name: "Resurrect Dead Wizards",
			type: "Arcana",
			expansion: "Undermountain",
			requiredClerics: 3,
			requiredGold: 5,
			rewardPoints: 6,
			rewardWizards: 3
		},
		{
			id: 17,
			name: "Study in the Librarium",
			type: "Arcana",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredRogues: 2,
			requiredWizards: 5,
			requiredGold: 5,
			rewardPoints: 11,
			rewardEffect: "After you take an action that allows you to play any Intrigue card, draw an Intrigue card.  You can play that card immediately without taking an action."
		},
		{
			id: 18,
			name: "Survive a Meeting With Halaster",
			type: "Arcana",
			expansion: "Undermountain",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredAdventurers: 1,
			rewardPoints: 15,
			rewardEffect: "Draw an Intrigue card for each wizard you used to complete this Quest."
		},
		{
			id: 19,
			name: "Establish Cult Cell",
			type: "Arcana",
			expansion: "Skullport",
			requiredRogues: 2,
			requiredWizards: 2,
			requiredGold: 3,
			rewardPoints: 18,
			rewardFighters: 2,
			rewardWizards: 1,
			rewardIntrigue: 1,
			rewardCorruption: 3
		},
		{
			id: 20,
			name: "Investigate Thayan Vessel",
			type: "Arcana",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 2,
			requiredRogues: 2,
			requiredWizards: 2,
			requiredGold: 2,
			rewardPoints: 13,
			rewardAdventurers: 2,
			rewardIntrigue: 2
		},
		{
			id: 21,
			name: "Recruit Academy Castoffs",
			type: "Arcana",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredFighters: 1,
			requiredWizards: 1,
			requiredGold: 2,
			rewardPoints: 8,
			rewardEffect: "Whenever you assign an agent to Blackstaff Tower, you can take another wizard and corruption and place them in your Tavern."
		},
		{
			id: 22,
			name: "Renew Guards and Wards",
			type: "Arcana",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredWizards: 2,
			requiredGold: 2,

			rewardPoints: 9,
			rewardEffect: "Return up to 2 corruption from your Tavern to the Corruption track."
		},
		{
			id: 23,
			name: "Seal an Entrance to Skullport",
			type: "Arcana",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 2,
			requiredRogues: 2,
			requiredWizards: 2,
			rewardPoints: 10,
			rewardEffect: "Return up to 3 corruption from your Tavern to the Corruption track."
		},
		{
			id: 24,
			name: "Uncover Forbidden Lore",
			type: "Arcana",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredRogues: 2,
			requiredWizards: 3,
			rewardPoints: 17,
			rewardEffect: "Whenever you assign an agent to Waterdeep Harbor, you can play up to another 2 Intrigue cards.  If you do so, take 1 corruption from the Corruption track and place it in your Tavern."
		},
		{
			id: 25,
			name: "Ally With House Thann",
			type: "Commerce",
			requiredClerics: 1,
			requiredRogues: 3,
			requiredWizards: 1,
			requiredGold: 8,
			rewardPoints: 25,
		},
		{
			id: 26,
			name: "Bribe the Shipwrights",
			type: "Commerce",
			isPlotQuest: true,
			requiredRogues: 4,
			requiredWizards: 1,
			requiredGold: 4,
			rewardPoints: 10,
			rewardEffect: "Whenever you take an action that provides any gold, also take a rogue from the supply and place it in your Tavern."
		},
		{
			id: 27,
			name: "Establish New Merchant Guild",
			type: "Commerce",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredFighters: 2,
			requiredGold: 4,
			rewardPoints: 8,
			rewardEffect: "Whenever you complete a Commerce Quest, you score 2 points."
		},
		{
			id: 28,
			name: "Impersonate Adarbrent Noble",
			type: "Commerce",
			requiredClerics: 1,
			requiredFighters: 2,
			requiredRogues: 2,
			requiredWizards: 1,
			requiredGold: 4,
			rewardPoints: 18,
			rewardIntrigue: 2,
		},
		{
			id: 29,
			name: "Infiltrate Builder's Hall",
			type: "Commerce",
			isPlotQuest: true,
			requiredFighters: 2,
			requiredRogues: 2,
			requiredGold: 4,
			rewardPoints: 6,
			rewardEffect: "Whenever you buy a Building, you score 4 points."
		},
		{
			id: 30,
			name: "Loot the Crypt of Chauntea",
			type: "Commerce",
			requiredClerics: 1,
			requiredRogues: 3,
			requiredGold: 2,
			rewardPoints: 7,
			rewardIntrigue: 1,
			rewardEffect: "Draw a quest from the deck."
		},
		{
			id: 31,
			name: "Lure Artisans of Mirabar",
			type: "Commerce",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 1,
			requiredGold: 2,
			rewardPoints: 4,
			rewardEffect: "Put 1 Building from Builder's Hall into play under your control at no cost."
		},
		{
			id: 32,
			name: "Placate the Walking Statue",
			type: "Commerce",
			requiredClerics: 2,
			requiredRogues: 2,
			requiredGold: 4,

			rewardPoints: 10,
			rewardEffect: "Draw 1 Building from the stack and put it into play under your control at no cost."
		},
		{
			id: 33,
			name: "Safeguard Eltorchul Mage",
			type: "Commerce",
			requiredFighters: 1,
			requiredRogues: 1,
			requiredWizards: 1,
			requiredGold: 4,
			rewardPoints: 4,
			rewardWizards: 2
		},
		{
			id: 34,
			name: "Send Aid to the Harpers",
			type: "Commerce",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 1,
			requiredGold: 4,
			rewardPoints: 15,
			rewardEffect: "Choose an opponent to gain 4 gold."
		},
		{
			id: 35,
			name: "Spy on the House of Light",
			type: "Commerce",
			requiredFighters: 3,
			requiredRogues: 2,
			requiredGold: 2,
			rewardPoints: 6,
			rewardGold: 6
		},
		{
			id: 36,
			name: "Thin the City Watch",
			type: "Commerce",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 1,
			requiredGold: 4,
			rewardPoints: 9,
			rewardRogues: 4
		},
		{
			id: 37,
			name: "Obtain Builder's Plans",
			type: "Commerce",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredFighters: 2,
			requiredRogues: 2,
			requiredWizards: 1,
			requiredGold: 10,
			rewardPoints: 13,
			rewardEffect: "Once per round, you can assign an agent to a Building in Builder's Hall.  You immediately use the effect of that Building as though you controlled it."
		},
		{
			id: 38,
			name: "Ransack Whitehelm's Tomb",
			type: "Commerce",
			expansion: "Undermountain",
			requiredClerics: 2,
			requiredFighters: 3,
			requiredRogues: 4,
			requiredGold: 10,
			rewardPoints: 40
		},
		{
			id: 39,
			name: "Recruit for City Watch",
			type: "Commerce",
			expansion: "Undermountain",
			requiredClerics: 1,
			requiredWizards: 1,
			rewardPoints: 8,
			rewardEffect: "Take 3 fighters and 3 rogues if you immediately spend 10 gold."
		},
		{
			id: 40,
			name: "Sponsor Bounty Hunters",
			type: "Commerce",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredFighters: 4,
			requiredRogues: 3,
			requiredGold: 6,
			rewardPoints: 12,
			rewardEffect: "Whenever you take a Commerce Quest, take 4 gold from the supply and place it in your Tavern."
		},
		{
			id: 41,
			name: "Steal Gems from the Bone Throne",
			type: "Commerce",
			expansion: "Undermountain",
			requiredRogues: 4,
			requiredWizards: 2,
			rewardPoints: 7,
			rewardGold: 10
		},
		{
			id: 42,
			name: "Threaten the Builders' Guilds",
			type: "Commerce",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredFighters: 2,
			requiredRogues: 4,
			requiredWizards: 2,
			requiredGold: 10,
			rewardPoints: 13,
			rewardEffect: "Immediately put all face up Buildings in Builder's Hall in play under your control at no cost."
		},
		{
			id: 43,
			name: "Defame Rival Business",
			type: "Commerce",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredFighters: 2,
			requiredRogues: 2,
			requiredGold: 4,
			rewardPoints: 9,
			rewardEffect: "Whenever you purchase a Building, you can remove a corruption from your Tavern and place it on any action space."
		},
		{
			id: 44,
			name: "Donate to the City",
			type: "Commerce",
			expansion: "Skullport",
			requiredClerics: 2,
			requiredWizards: 1,
			requiredGold: 10,
			rewardPoints: 13,
			rewardEffect: "Return up to 3 corruption from your Tavern to the Corruption track."
		},
		{
			id: 45,
			name: "Extort Aurora",
			type: "Commerce",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredRogues: 2,
			requiredGold: 4,
			rewardPoints: 8,
			rewardEffect: "Whenever you assign an agent to Aurora's Realms Shop, you can take another 4 gold and 1 corruption and place them in your Tavern."
		},
		{
			id: 46,
			name: "Fund Alchemical Research",
			type: "Commerce",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredRogues: 1,
			requiredWizards: 2,
			requiredGold: 4,
			rewardPoints: 20,
			rewardGold: 12,
			rewardCorruption: 3
		},
		{
			id: 47,
			name: "Fund Pilgrimage of Waukeen",
			type: "Commerce",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 2,
			requiredGold: 5,
			rewardPoints: 16
		},
		{
			id: 48,
			name: "Pay Fines",
			type: "Commerce",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredRogues: 3,
			requiredGold: 4,
			rewardPoints: 4,
			rewardEffect: "Return up to 2 corruption from your Tavern to the Corruption track."
		},
		{
			id: 49,
			name: "Convert a Noble to Lathander",
			type: "Piety",
			requiredClerics: 2,
			requiredFighters: 1,
			rewardPoints: 8,
			rewardEffect: "Take a quest from Cliffwatch Inn."
		},
		{
			id: 50,
			name: "Create a Shrine to Oghma",
			type: "Piety",
			requiredClerics: 5,
			requiredGold: 2,
			rewardPoints: 25
		},
		{
			id: 51,
			name: "Defend the Tower of Luck",
			type: "Piety",
			isPlotQuest: true,
			requiredClerics: 2,
			requiredFighters: 1,
			requiredRogues: 1,
			requiredWizards: 1,
			rewardPoints: 0,
			rewardEffect: "Once at the start of each round, take an adventurer from the supply and place it in your Tavern."
		},
		{
			id: 52,
			name: "Discover Hidden Temple of Lolth",
			type: "Piety",
			requiredClerics: 2,
			requiredFighters: 1,
			requiredRogues: 1,
			rewardPoints: 10,
			rewardEffect: "Take a quest from Cliffwatch Inn."
		},
		{
			id: 53,
			name: "Eliminate Vampire Coven",
			type: "Piety",
			requiredClerics: 2,
			requiredFighters: 2,
			requiredRogues: 1,
			rewardPoints: 11,
			rewardGold: 4
		},
		{
			id: 54,
			name: "Form an Alliance With the Rashemi",
			type: "Piety",
			requiredClerics: 2,
			requiredWizards: 1,
			rewardPoints: 10,
			rewardEffect: "Take a quest from Cliffwatch Inn."
		},
		{
			id: 55,
			name: "Heal Fallen Gray Hand Soldiers",
			type: "Piety",
			requiredClerics: 2,
			requiredWizards: 1,
			requiredGold: 4,
			rewardPoints: 6,
			rewardFighters: 6
		},
		{
			id: 56,
			name: "Perform the Penance of Duty",
			type: "Piety",
			requiredClerics: 2,
			requiredFighters: 2,
			requiredGold: 4,
			rewardPoints: 12,
			rewardClerics: 1,
			rewardFighters: 1
		},
		{
			id: 57,
			name: "Produce a Miracle for the Masses",
			type: "Piety",
			isPlotQuest: true,
			requiredClerics: 2,
			requiredGold: 4,
			rewardPoints: 5,
			rewardEffect: "Once per round, whenever you take an action that provides any clerics, you can also replace a fighter, rogue or wizard in your Tavern with a cleric."
		},
		{
			id: 58,
			name: "Protect the House of Wonder",
			type: "Piety",
			isPlotQuest: true,
			requiredClerics: 2,
			requiredFighters: 1,
			requiredGold: 2,
			rewardPoints: 8,
			rewardEffect: "Whenever you complete a Piety Quest, you score 2 points."
		},
		{
			id: 59,
			name: "Recruit Paladins for Tyr",
			type: "Piety",
			requiredClerics: 2,
			requiredFighters: 4,
			requiredGold: 4,
			rewardPoints: 10,
			rewardClerics: 3
		},
		{
			id: 60,
			name: "Seal Gate to Cyric's Realm",
			type: "Piety",
			requiredClerics: 2,
			requiredRogues: 3,
			requiredGold: 4,
			rewardPoints: 20
		},
		{
			id: 61,
			name: "Diplomatic Mission to Suzail",
			type: "Piety",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredClerics: 3,
			requiredFighters: 3,
			requiredGold: 3,
			rewardPoints: 10,
			rewardEffect: "You can complete face-up quests at Cliffwatch Inn as though they were active Quests."
		},
		{
			id: 62,
			name: "Establish Temple to Ibrandul",
			type: "Piety",
			expansion: "Undermountain",
			requiredClerics: 3,
			requiredRogues: 4,
			requiredGold: 5,
			rewardPoints: 11,
			rewardClerics: 1,
			rewardFighters: 1,
			rewardRogues: 1,
			rewardWizards: 1,
			rewardEffect: "Take all quests from Cliffwatch Inn."
		},
		{
			id: 63,
			name: "Plunder the Island Temple",
			type: "Piety",
			expansion: "Undermountain",
			requiredClerics: 5,
			requiredFighters: 2,
			requiredRogues: 2,
			requiredWizards: 1,
			rewardPoints: 40,
		},
		{
			id: 64,
			name: "Rescue Clerics of Tymora",
			type: "Piety",
			expansion: "Undermountain",
			requiredFighters: 6,
			requiredWizards: 2,
			rewardPoints: 10,
			rewardClerics: 3
		},
		{
			id: 65,
			name: "Root Out Loviatar's Faithful",
			type: "Piety",
			expansion: "Undermountain",
			requiredFighters: 1,
			requiredWizards: 1,
			requiredAdventurers: 4,
			rewardPoints: 15,
			rewardEffect: "Plus 2 points for each cleric you used to complete this quest."
		},
		{
			id: 66,
			name: "Sanctify a Desecrated Temple",
			type: "Piety",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredClerics: 4,
			requiredFighters: 2,
			requiredGold: 5,
			rewardPoints: 13,
			rewardEffect: "Whenever you take a Piety Quest, take a cleric from the supply and place it in your Tavern."
		},
		{
			id: 67,
			name: "Banish Evil Spirits",
			type: "Piety",
			expansion: "Skullport",
			requiredClerics: 2,
			requiredFighters: 2,
			requiredWizards: 1,
			rewardPoints: 5,
			rewardAdventurers: 1,
			rewardEffect: "Return up to 2 corruption from your Tavern to the Corruption track."
		},
		{
			id: 68,
			name: "Enter the Tower of Seven Woes",
			type: "Piety",
			expansion: "Skullport",
			requiredAdventurers: 7,
			rewardPoints: 19,
			rewardClerics: 3,
			rewardCorruption: 4
		},
		{
			id: 69,
			name: "Give Honor to Mask",
			type: "Piety",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredRogues: 1,
			requiredGold: 2,
			rewardPoints: 8,
			rewardEffect: "Whenever you assign an agent to the Plinth, you can take another cleric and corruption and place them in your Tavern."
		},
		{
			id: 70,
			name: "Institute Reforms",
			type: "Piety",
			expansion: "Skullport",
			requiredClerics: 4,
			requiredFighters: 1,
			requiredRogues: 1,
			requiredGold: 2,
			rewardPoints: 13,
			rewardEffect: "Return up to 3 corruption from your Tavern to the Corruption track."
		},
		{
			id: 71,
			name: "Protect Converts to Eilistraee",
			type: "Piety",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredClerics: 3,
			requiredFighters: 2,
			requiredWizards: 1,
			rewardPoints: 10,
			rewardEffect: "Once on your turn, whenever you return any corruption from your Tavern to the Corruption track, you can return another corruption."
		},
		{
			id: 72,
			name: "Sanctify Temple to Oghma",
			type: "Piety",
			expansion: "Skullport",
			requiredClerics: 2,
			requiredWizards: 1,
			requiredGold: 5,
			rewardPoints: 18
		},
		{
			id: 73,
			name: "Build a Reputation in Skullport",
			type: "Skullduggery",
			requiredFighters: 1,
			requiredRogues: 3,
			requiredGold: 4,
			rewardPoints: 10,
			rewardIntrigue: 1
		},
		{
			id: 74,
			name: "Establish Harpers Safe House",
			type: "Skullduggery",
			requiredFighters: 2,
			requiredRogues: 3,
			requiredGold: 2,
			rewardPoints: 8,
			rewardEffect: "Plus 2 points for each Building you control."
		},
		{
			id: 75,
			name: "Establish Shadow Thieves' Guild",
			type: "Skullduggery",
			requiredFighters: 1,
			requiredRogues: 8,
			requiredWizards: 1,
			rewardPoints: 25
		},
		{
			id: 76,
			name: "Expose Cult Corruption",
			type: "Skullduggery",
			requiredClerics: 1,
			requiredRogues: 4,
			rewardPoints: 4,
			rewardClerics: 2
		},
		{
			id: 77,
			name: "Fence Goods for Duke of Darkness",
			type: "Skullduggery",
			isPlotQuest: true,
			requiredFighters: 1,
			requiredRogues: 3,
			requiredGold: 4,
			rewardPoints: 6,
			rewardEffect: "Whenever you take an action that provides any rogues, also take 2 gold from the supply."
		},
		{
			id: 78,
			name: "Install a Spy in Castle Waterdeep",
			type: "Skullduggery",
			isPlotQuest: true,
			requiredRogues: 2,
			requiredGold: 4,
			rewardPoints: 8,
			rewardEffect: "Whenever you complete a Skullduggery Quest, you score 2 points."
		},
		{
			id: 79,
			name: "Place a Sleeper Agent in Skullport",
			type: "Skullduggery",
			isPlotQuest: true,
			requiredFighters: 1,
			requiredRogues: 4,
			requiredWizards: 1,
			rewardPoints: 0,
			rewardEffect: "Whenever you play an Intrigue card, you score 2 points."
		},
		{
			id: 80,
			name: "Prison Break",
			type: "Skullduggery",
			requiredRogues: 4,
			requiredWizards: 2,
			requiredGold: 2,
			rewardPoints: 14,
			rewardFighters: 2,
			rewardEffect: "Immediately play an Intrigue card without taking an action."
		},
		{
			id: 81,
			name: "Procure Stolen Goods",
			type: "Skullduggery",
			requiredRogues: 3,
			requiredGold: 6,
			rewardPoints: 8,
			rewardIntrigue: 2,
		},
		{
			id: 82,
			name: "Raid on Undermountain",
			type: "Skullduggery",
			requiredClerics: 1,
			requiredFighters: 2,
			requiredRogues: 4,
			requiredWizards: 1,
			rewardPoints: 20,
			rewardGold: 2
		},
		{
			id: 83,
			name: "Steal from House Adarbrent",
			type: "Skullduggery",
			requiredFighters: 1,
			requiredRogues: 4,
			requiredWizards: 1,
			rewardPoints: 10,
			rewardGold: 6
		},
		{
			id: 84,
			name: "Take Over Rival Organization",
			type: "Skullduggery",
			requiredFighters: 1,
			requiredRogues: 2,
			requiredWizards: 1,
			requiredGold: 6,
			rewardPoints: 10,
			rewardRogues: 4,
		},
		{
			id: 85,
			name: "Ally with the Xanathar's Guild",
			type: "Skullduggery",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredFighters: 2,
			requiredRogues: 5,
			requiredWizards: 1,
			requiredGold: 5,
			rewardPoints: 10,
			rewardEffect: "Whenever you take a Skullduggery Quest, take 2 rogues from the supply and place them in your Tavern."
		},
		{
			id: 86,
			name: "Break Into Blackstaff Tower",
			type: "Skullduggery",
			expansion: "Undermountain",
			requiredClerics: 1,
			requiredRogues: 7,
			requiredWizards: 2,
			requiredGold: 6,
			rewardPoints: 40
		},
		{
			id: 87,
			name: "Defend the Lanceboard Room",
			type: "Skullduggery",
			expansion: "Undermountain",
			requiredFighters: 3,
			requiredRogues: 6,
			requiredWizards: 2,
			requiredGold: 10,
			rewardPoints: 12,
			rewardAdventurers: 8
		},
		{
			id: 88,
			name: "Impersonate Tax Collector",
			type: "Skullduggery",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredFighters: 1,
			requiredRogues: 4,
			requiredWizards: 1,
			requiredGold: 5,
			rewardPoints: 9,
			rewardEffect: "Whenever you assign an agent to a Building you control, you also gain the owner benefit."
		},
		{
			id: 89,
			name: "Survive Arcturia's Transformation",
			type: "Skullduggery",
			expansion: "Undermountain",
			requiredFighters: 6,
			requiredGold: 5,
			rewardPoints: 6,
			rewardRogues: 6
		},
		{
			id: 90,
			name: "Unleash Crime Spree",
			type: "Skullduggery",
			expansion: "Undermountain",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 1,
			requiredWizards: 1,
			rewardPoints: 12,
			rewardEffect: "Plus 10 points if you immediately return 4 rogues from your Tavern to the supply."
		},
		{
			id: 91,
			name: "Bury the Bodies",
			type: "Skullduggery",
			expansion: "Skullport",
			requiredFighters: 2,
			requiredRogues: 3,
			requiredGold: 2,
			rewardPoints: 20,
			rewardCorruption: 2
		},
		{
			id: 92,
			name: "Expand Guild Activities",
			type: "Skullduggery",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredFighters: 1,
			requiredRogues: 2,
			requiredGold: 2,
			rewardPoints: 8,
			rewardEffect: "Whenever you assign an agent to the Grinning Lion Tavern, you can take another 2 rogues and 1 corruption and place them in your Tavern."
		},
		{
			id: 93,
			name: "Rescue a Victim from the Skulls",
			type: "Skullduggery",
			expansion: "Skullport",
			requiredFighters: 2,
			requiredRogues: 4,
			requiredWizards: 1,
			rewardPoints: 9,
			rewardAdventurers: 1,
			rewardEffect: "Return up to 1 corruption from your Tavern to the Corruption track."
		},
		{
			id: 94,
			name: "Save Kidnapped Nobles",
			type: "Skullduggery",
			expansion: "Skullport",
			requiredRogues: 6,
			requiredWizards: 2,
			requiredGold: 5,
			rewardPoints: 9,
			rewardFighters: 4,
			rewardEffect: "Return up to 3 corruption from your Tavern to the Corruption track."
		},
		{
			id: 95,
			name: "Shelter Zhentarim Agents",
			type: "Skullduggery",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredFighters: 3,
			requiredWizards: 2,
			rewardPoints: 16,
			rewardCorruption: 1,
			rewardEffect: "Once on your turn, whenever you gain any corruption, draw an Intrigue card."
		},
		{
			id: 96,
			name: "Swindle the Builder's Guilds",
			type: "Skullduggery",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 2,
			requiredRogues: 3,
			requiredGold: 5,
			rewardPoints: 13,
			rewardCorruption: 3,
			rewardEffect: "Put 2 face-up Buildings in Builder's Hall in play under your control at no cost."
		},
		{
			id: 97,
			name: "Ambush Artor Morlin",
			type: "Warfare",
			requiredClerics: 1,
			requiredFighters: 3,
			requiredRogues: 1,
			rewardPoints: 8,
			rewardGold: 4
		},
		{
			id: 98,
			name: "Bolster City Guard",
			type: "Warfare",
			requiredFighters: 9,
			requiredRogues: 2,
			rewardPoints: 25
		},
		{
			id: 99,
			name: "Bolster Griffon Cavalry",
			type: "Warfare",
			isPlotQuest: true,
			requiredFighters: 4,
			requiredGold: 4,
			rewardPoints: 6,
			rewardEffect: "Whenever you take an action that provides any fighters, also take a fighter from the supply and place it in your Tavern."
		},
		{
			id: 100,
			name: "Confront the Xanathar",
			type: "Warfare",
			requiredClerics: 1,
			requiredFighters: 4,
			requiredRogues: 2,
			requiredWizards: 1,
			rewardPoints: 20,
			rewardGold: 2
		},
		{
			id: 101,
			name: "Defeat Uprising from Undermountain",
			type: "Warfare",
			requiredClerics: 1,
			requiredFighters: 3,
			requiredRogues: 1,
			requiredGold: 2,
			rewardPoints: 11,
			rewardFighters: 2,
		},
		{
			id: 102,
			name: "Deliver Weapons to Selune's Temple",
			type: "Warfare",
			requiredFighters: 4,
			requiredRogues: 1,
			requiredWizards: 1,
			requiredGold: 2,
			rewardPoints: 9,
			rewardClerics: 2
		},
		{
			id: 103,
			name: "Deliver an Ultimatum",
			type: "Warfare",
			requiredFighters: 4,
			requiredRogues: 1,
			requiredWizards: 1,
			rewardPoints: 11,
			rewardGold: 4
		},
		{
			id: 104,
			name: "Quell Mercenary Uprising",
			type: "Warfare",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredFighters: 4,
			rewardPoints: 8,
			rewardEffect: "Whenever you complete a Warfare Quest, you score 2 points."
		},
		{
			id: 105,
			name: "Raid Orc Stronghold",
			type: "Warfare",
			requiredFighters: 4,
			requiredRogues: 2,
			rewardPoints: 8,
			rewardGold: 4
		},
		{
			id: 106,
			name: "Recruit Lieutenant",
			type: "Warfare",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredFighters: 5,
			requiredRogues: 1,
			requiredWizards: 1,
			rewardPoints: 0,
			rewardEffect: "Add the Lieutenant to your pool of agents for the rest of the game."
		},
		{
			id: 107,
			name: "Repel Seawraiths",
			type: "Warfare",
			requiredClerics: 1,
			requiredFighters: 4,
			requiredWizards: 1,
			rewardPoints: 15,
			rewardGold: 2
		},
		{
			id: 108,
			name: "Train Bladesingers",
			type: "Warfare",
			requiredFighters: 3,
			requiredWizards: 1,
			rewardPoints: 4,
			rewardFighters: 1,
			rewardWizards: 1,
		},
		{
			id: 109,
			name: "Battle in Muiral's Gauntlet",
			type: "Warfare",
			expansion: "Undermountain",
			requiredClerics: 2,
			requiredFighters: 7,
			requiredWizards: 2,
			requiredGold: 2,
			rewardPoints: 40
		},
		{
			id: 110,
			name: "Defend the Yawning Portal",
			type: "Warfare",
			expansion: "Undermountain",
			requiredClerics: 3,
			requiredFighters: 6,
			requiredRogues: 1,
			requiredWizards: 1,
			rewardPoints: 15,
			rewardAdventurers: 2,
			rewardEffect: "Return up to 3 of your assigned agents to your pool."
		},
		{
			id: 111,
			name: "Destroy a Temple of Selvetarm",
			type: "Warfare",
			expansion: "Undermountain",
			requiredClerics: 1,
			requiredFighters: 2,
			requiredGold: 2,
			rewardPoints: 10,
			rewardEffect: "Plus 10 points if you immediately return 4 fighters from your Tavern to the supply."
		},
		{
			id: 112,
			name: "Recover the Flame of the North",
			type: "Warfare",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredFighters: 5,
			requiredRogues: 3,
			requiredWizards: 1,
			requiredGold: 3,
			rewardPoints: 10,
			rewardEffect: "Whenever you take a Warfare Quest, take 2 fighters from the supply and place them in your Tavern."
		},
		{
			id: 113,
			name: "Seize Citadel of the Bloody Hand",
			type: "Warfare",
			expansion: "Undermountain",
			isPlotQuest: true,
			requiredClerics: 1,
			requiredFighters: 4,
			requiredWizards: 2,
			rewardPoints: 6,
			rewardEffect: "Whenever you complete a Quest, you may return an adventurer used to complete that Quest to your Tavern."
		},
		{
			id: 114,
			name: "Wake the Six Sleepers",
			type: "Warfare",
			expansion: "Undermountain",
			requiredClerics: 3,
			requiredRogues: 3,
			rewardPoints: 8,
			rewardFighters: 6,
		},
		{
			id: 115,
			name: "Assassinate Rivals",
			type: "Warfare",
			expansion: "Skullport",
			requiredFighters: 4,
			requiredRogues: 1,
			rewardPoints: 16,
			rewardCorruption: 2,
			rewardEffect: "Each opponent returns an adventurer from his or her Tavern to the supply."
		},
		{
			id: 116,
			name: "Fix the Champion's Games",
			type: "Warfare",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredFighters: 3,
			requiredGold: 2,
			rewardPoints: 8,
			rewardEffect: "Whenever you assign an agent to the Field of Triumph, you can take another 2 fighters and 1 corruption and place them in your Tavern."
		},
		{
			id: 117,
			name: "Improve Prison Security",
			type: "Warfare",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 4,
			requiredRogues: 2,
			requiredGold: 4,
			rewardPoints: 8,
			rewardEffect: "Remove up to 3 corruption in your Tavern from the game."
		},
		{
			id: 118,
			name: "Patrol Dock Ward",
			type: "Warfare",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 3,
			requiredRogues: 2,
			requiredGold: 2,
			rewardPoints: 9,
			rewardRogues: 4
		},
		{
			id: 119,
			name: "Train Castle Guards",
			type: "Warfare",
			expansion: "Skullport",
			isPlotQuest: true,
			requiredFighters: 2,
			requiredWizards: 1,
			requiredGold: 5,
			rewardPoints: 10,
			rewardEffect: "Whenever any player takes starting player, you and that player also take a fighter from the supply."
		},
		{
			id: 120,
			name: "Uncover Drow Plot",
			type: "Warfare",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 5,
			requiredRogues: 2,
			requiredGold: 5,
			rewardPoints: 18,
			rewardEffect: "Return up to 2 corruption from your Tavern to the Corruption track."
		},
		{
			id: 121,
			name: "Fend Off Bandits",
			type: "Mandatory",
			requiredFighters: 2,
			requiredWizards: 1,
			rewardPoints: 2
		},
		{
			id: 122,
			name: "Foil the Zhentarim",
			type: "Mandatory",
			requiredFighters: 1,
			requiredRogues: 1,
			requiredWizards: 1,
			rewardPoints: 2
		},
		{
			id: 123,
			name: "Placate Angry Merchants",
			type: "Mandatory",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredWizards: 1,
			rewardPoints: 4
		},
		{
			id: 124,
			name: "Quell Riots",
			type: "Mandatory",
			requiredClerics: 2,
			requiredFighters: 1,
			rewardPoints: 4
		},
		{
			id: 125,
			name: "Repel Drow Invaders",
			type: "Mandatory",
			requiredClerics: 1,
			requiredRogues: 1,
			rewardPoints: 2
		},
		{
			id: 126,
			name: "Stamp Out Cultists",
			type: "Mandatory",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 1,
			rewardPoints: 2
		},
		{
			id: 127,
			name: "Evade Assassin",
			type: "Mandatory",
			expansion: "Undermountain",
			requiredRogues: 2,
			requiredWizards: 1,
			rewardIntrigue: 1
		},
		{
			id: 128,
			name: "Subdue Illithid Menace",
			type: "Mandatory",
			expansion: "Undermountain",
			requiredClerics: 1,
			requiredFighters: 2,
			rewardIntrigue: 1
		},
		{
			id: 129,
			name: "Unveil Abyssal Agent",
			type: "Mandatory",
			expansion: "Undermountain",
			requiredClerics: 1,
			requiredWizards: 1,
			rewardIntrigue: 1
		},
		{
			id: 130,
			name: "Clear Rust Monster Nest",
			type: "Mandatory",
			expansion: "Skullport",
			requiredFighters: 1,
			requiredWizards: 1,
			requiredGold: 2,
			rewardPoints: 2
		},
		{
			id: 131,
			name: "Cover Up a Scandal",
			type: "Mandatory",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredFighters: 1,
			requiredRogues: 1,
			requiredWizards: 1,
			rewardPoints: 2,
			rewardEffect: "Return up to 1 corruption from your Tavern to the Corruption track."
		},
		{
			id: 132,
			name: "Hunt Hidden Ghoul",
			type: "Mandatory",
			expansion: "Skullport",
			requiredClerics: 1,
			requiredRogues: 1,
			requiredGold: 2,
			rewardPoints: 2
		}
	]
});

export default Quest;
